### ISSUE TITLE
Work

### ISSUE THREAD

**Issue by keungbryan** [eric-yhy/teamform-seed#88]
Is there any thing I can do?
(′д｀ )…彡…彡

**Comment by vlee-harmonicinc** [comment]
mmm...how about unit test? it need lot of mock data to test most of the function.
Also, I found member.html is not start when I doing accept invite, so you can ask Mike and Ronald if they are too busy to finish it?
You can also ask if Mike and Ronald want to modify their page, such as show team name instead of team id. This is quite messy since load data from firebase consume time and AngularJs seen to be asynchronous and it waste me lot of time to do callback and checking console.
Also, it seem to be unbalance workload, will you want to do the smart generator of admin that generate team after deadline?
